param(
    [string]$Manifest = "$PSScriptRoot\..\docs\wordbook-sample\words.jsonl",
    [string]$OutDir = "$PSScriptRoot\..\docs\audio-sample",
    [string]$EmbedHeader = "",
    [string]$Voice = "Microsoft Zira Desktop"
)
$ErrorActionPreference = 'Stop'
Add-Type -AssemblyName System.Speech
$utf8 = New-Object System.Text.UTF8Encoding($false)
New-Item -ItemType Directory -Force -Path $OutDir | Out-Null
$entries = @(Get-Content -LiteralPath $Manifest -Encoding UTF8 | Where-Object { $_.Trim() } | ForEach-Object { $_ | ConvertFrom-Json })
$synth = New-Object System.Speech.Synthesis.SpeechSynthesizer
$hash = [System.Security.Cryptography.SHA256]::Create()
$header = New-Object System.Text.StringBuilder
[void]$header.AppendLine('// Generated by scripts/prepare_audio.ps1. English voice: ' + $Voice)
[void]$header.AppendLine('#pragma once')
[void]$header.AppendLine('#include <cstddef>')
[void]$header.AppendLine('#include <cstdint>')
[void]$header.AppendLine('#include <cstring>')
[void]$header.AppendLine('namespace wordmon { namespace speech {')
$rows = @()
try {
    $synth.SelectVoice($Voice)
    $synth.Rate = -1
    $synth.Volume = 100
    $format = New-Object System.Speech.AudioFormat.SpeechAudioFormatInfo(11025, [System.Speech.AudioFormat.AudioBitsPerSample]::Eight, [System.Speech.AudioFormat.AudioChannel]::Mono)
    $index = 0
    foreach ($entry in $entries) {
        $word = [string]$entry.w
        if (-not $word.Trim() -or $word.Length -gt 80 -or $word -match '[\x00-\x1f]') { throw 'Invalid word' }
        $digest = [BitConverter]::ToString($hash.ComputeHash($utf8.GetBytes($word))).Replace('-', '').ToLower().Substring(0,16)
        $name = "speech-$digest.wav"
        $path = Join-Path $OutDir $name
        $synth.SetOutputToWaveFile($path, $format)
        $synth.Speak($word)
        $synth.SetOutputToNull()
        $bytes = [System.IO.File]::ReadAllBytes($path)
        if ($bytes.Length -gt 49152) { throw "Audio too long for device: $word" }
        $foundData = $false
        for ($chunk = 12; $chunk + 8 -le $bytes.Length;) {
            $count = [BitConverter]::ToUInt32($bytes, $chunk + 4)
            if ([System.Text.Encoding]::ASCII.GetString($bytes, $chunk, 4) -eq 'data') {
                if ($count -eq 0 -or $count -gt 44100) { throw "Audio exceeds four seconds: $word" }
                $foundData = $true
                break
            }
            $chunk += 8 + $count + ($count % 2)
        }
        if (-not $foundData) { throw "WAV data missing: $word" }
        $entry | Add-Member -NotePropertyName s -NotePropertyValue $name -Force
        # Preserve existing illustrations when exporting a complete wordbook folder.
        if ($entry.a -and ([string]$entry.a -match '^[A-Za-z0-9_-][A-Za-z0-9_.-]*$') -and ([string]$entry.a -notmatch '\.\.')) {
            $sourceArt = Join-Path (Split-Path -Parent ([System.IO.Path]::GetFullPath($Manifest))) ([string]$entry.a)
            $targetArt = [System.IO.Path]::GetFullPath((Join-Path $OutDir ([string]$entry.a)))
            if ((Test-Path -LiteralPath $sourceArt) -and $sourceArt -ne $targetArt) {
                Copy-Item -LiteralPath $sourceArt -Destination $targetArt -Force
            }
        }
        if ($EmbedHeader) {
            [void]$header.AppendLine("static const uint8_t clip$index[] = {")
            for ($offset = 0; $offset -lt $bytes.Length; $offset += 24) {
                $last = [Math]::Min($offset + 23, $bytes.Length - 1)
                [void]$header.AppendLine(($bytes[$offset..$last] -join ',') + ',')
            }
            [void]$header.AppendLine('};')
            $escaped = $word.Replace('\', '\\').Replace('"', '\"')
            $rows += "{`"$escaped`", clip$index, sizeof(clip$index)},"
        }
        Write-Host "$word -> $name ($($bytes.Length) bytes)"
        $index++
    }
    $jsonl = ($entries | ForEach-Object { ConvertTo-Json $_ -Compress }) -join "`n"
    [System.IO.File]::WriteAllText((Join-Path $OutDir 'words.jsonl'), $jsonl + "`n", $utf8)
    if ($EmbedHeader) {
        [void]$header.AppendLine('struct Clip { const char* word; const uint8_t* data; size_t size; };')
        [void]$header.AppendLine('static const Clip clips[] = {')
        foreach ($row in $rows) { [void]$header.AppendLine($row) }
        [void]$header.AppendLine('};')
        [void]$header.AppendLine('inline const Clip* find(const char* word) { for (const auto& clip : clips) if (!strcmp(word, clip.word)) return &clip; return nullptr; }')
        [void]$header.AppendLine('} }')
        [System.IO.File]::WriteAllText([System.IO.Path]::GetFullPath($EmbedHeader), $header.ToString(), $utf8)
    }
} finally {
    $synth.Dispose()
    $hash.Dispose()
}
