"""Convert an SVG/PNG illustration into an LVGL ARGB8888 C++ header.

Usage (from the project root):
  .venv/Scripts/python.exe scripts/svg_to_header.py docs/apple.svg \
      --name apple --max-w 80 --max-h 88

SVG files are rasterized with Edge headless (cairo/svglib are not available
on this machine). The transparent margin is trimmed, the image is scaled to
fit the given box, and the result is emitted as a byte array in LVGL
ARGB8888 little-endian order (B, G, R, A per pixel).
"""

import argparse
import pathlib
import re
import subprocess
import tempfile

from PIL import Image

EDGE = pathlib.Path(r"C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe")


def render_svg(svg_path: pathlib.Path, out_png: pathlib.Path) -> None:
    # Read the viewBox to size the headless window exactly around the art.
    text = svg_path.read_text(encoding="utf-8", errors="replace")
    match = re.search(r'viewBox\s*=\s*["\'][^0-9]*(\d+)[ ,]+(\d+)[ ,]+(\d+)[ ,]+(\d+)', text)
    if not match:
        raise SystemExit("could not read viewBox from " + str(svg_path))
    width, height = int(match.group(3)), int(match.group(4))

    html = (
        "<!doctype html><html><head><style>"
        "html,body{margin:0;padding:0;background:transparent}"
        f"svg{{display:block;width:{width}px;height:{height}px}}"
        "</style></head><body>"
        + text.replace(
            f'viewBox="0 0 {width} {height}"',
            f'viewBox="0 0 {width} {height}" width="{width}" height="{height}"',
            1,
        )
        + "</body></html>"
    )
    with tempfile.TemporaryDirectory() as tmp:
        html_path = pathlib.Path(tmp) / "wrap.html"
        html_path.write_text(html, encoding="utf-8")
        cmd = [
            str(EDGE),
            "--headless=new",
            "--disable-gpu",
            "--hide-scrollbars",
            f"--screenshot={out_png}",
            f"--window-size={width},{height}",
            "--default-background-color=00000000",
            html_path.as_uri(),
        ]
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=60)
    if not out_png.exists():
        raise SystemExit(f"Edge render failed: {result.stderr[:400]}")
    print(f"rendered {svg_path.name} at {width}x{height} via Edge headless")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("source", type=pathlib.Path, help=".svg or .png input")
    parser.add_argument("--name", required=True, help="C++ symbol base name")
    parser.add_argument("--max-w", type=int, default=80)
    parser.add_argument("--max-h", type=int, default=88)
    parser.add_argument(
        "--out",
        type=pathlib.Path,
        default=pathlib.Path("include/assets"),
        help="output directory for the header (default include/assets)",
    )
    args = parser.parse_args()

    png_path = args.source.resolve()
    if args.source.suffix.lower() == ".svg":
        png_path = png_path.with_name(png_path.stem + "_render.png")
        render_svg(args.source.resolve(), png_path)

    image = Image.open(png_path).convert("RGBA")
    source_size = image.size
    image = image.crop(image.getchannel("A").getbbox())
    trimmed_size = image.size

    scale = min(args.max_w / image.width, args.max_h / image.height, 1.0)
    size = (
        max(1, round(image.width * scale)),
        max(1, round(image.height * scale)),
    )
    image = image.resize(size, Image.LANCZOS)

    pixels = image.tobytes()  # RGBA
    body = bytearray()
    for i in range(0, len(pixels), 4):
        r, g, b, a = pixels[i : i + 4]
        body += bytes((b, g, r, a))  # 0xAARRGGBB little-endian

    guard = f"WORDMON_ART_{args.name.upper()}_HPP"
    lines = [
        f"// Generated by scripts/svg_to_header.py from {args.source.name}.",
        f"// Source {source_size[0]}x{source_size[1]}, trimmed {trimmed_size[0]}x{trimmed_size[1]},",
        f"// output {size[0]}x{size[1]} ARGB8888 ({len(body)} bytes).",
        "#pragma once",
        "",
        '#include <stdint.h>',
        "",
        f"#ifndef {guard}",
        f"#define {guard}",
        "",
        "namespace wordmon {",
        "namespace art {",
        "",
        f"constexpr uint16_t k{args.name.capitalize()}W = {size[0]};",
        f"constexpr uint16_t k{args.name.capitalize()}H = {size[1]};",
        f"constexpr uint8_t k{args.name.capitalize()}[] = {{",
    ]
    for row_start in range(0, len(body), size[0] * 4):
        row = body[row_start : row_start + size[0] * 4]
        lines.append("    " + ",".join(str(v) for v in row) + ",")
    lines += [
        "};",
        "",
        f"}}  // namespace art",
        f"}}  // namespace wordmon",
        "",
        f"#endif  // {guard}",
        "",
    ]

    args.out.mkdir(parents=True, exist_ok=True)
    header = args.out / f"{args.name}_art.hpp"
    header.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {header} ({size[0]}x{size[1]}, {len(body)} bytes)")


if __name__ == "__main__":
    main()
